const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const USER_LOADED = "USER_LOADED";
const USER_LOADING = "USER_LOADING";

export default {
  AUTH_ERROR,
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  LOGOUT_SUCCESS,
  REGISTER_FAIL,
  REGISTER_SUCCESS,
  USER_LOADED,
  USER_LOADING
};
